"""relacionando categories con products v.4

Revision ID: 27df9f40bb1c
Revises: c83d12ac26e3
Create Date: 2025-08-17 00:00:54.606967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27df9f40bb1c'
down_revision: Union[str, Sequence[str], None] = 'c83d12ac26e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('products_sluck_key'), 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['slug'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'sluck')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sluck', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint(op.f('products_sluck_key'), 'products', ['sluck'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###
